### ISSUE TITLE
nuke plugin

### ISSUE THREAD

**Issue by Super-toad65** [BBXD/BBXD#12]
why not making better with rank system, so it's not possible to nuke an user with your powerlevel or above? 

Also, the "user 1" stuff is derp. my method could remove complicate code and get it cleaner

**Comment by JeDa** [comment]
The user 1 stuff got removed already. Please read the commits ¬¬

Also, regarding the nuke, well true. Allowing anyone with the power of it can be risky, as can happen as has happened before that an admin nukes the owner. I'll look forwards adding this.

**Comment by maorninja** [comment]
@JeDa he means on the nuke plugin, UID 1 can't get nuked. He wasn't making a reference to the registration, in which I agree. I didn't know that the case might happen where some random dude registers before the owner. Thanks @Super-toad65, for telling me this. Jeda, you did good.

I'm going to do some changes to the nuke:
-Its going to intergrated into the board: Its to make it more like MyBB
-Its no longer going to be called "nuke". I'm going to call it "delete user"
-It'll delete only if the user's rank is below 0. That means that the user needs to be banned in order to nuke him. Seeing how admins can't ban owners, this will block it. This is checked twice.
-You'll now need to have the permission to edit your profile **and** other profiles in order to nuke the user. Just the nuke permission isn't enough because a) no hypocrites and b) It makes sence.
